ViuTV:
  name:
    - ViuTV
  scraper:
    xmltv: 410274@http://epg.pw/xmltv/epg_HK.xml 
  refresh: today
  recap: 1
  preview: 1
NowNews:
  name:
    - Now新聞台
  scraper:
    xmltv: 410344@http://epg.pw/xmltv/epg_HK.xml 
  refresh: today
  recap: 1
  preview: 1
dwqws:
  name:
    - 大湾区卫视
  scraper:
    xmltv: 大湾区卫视@http://epg.112114.xyz/pp.xml
  refresh: today
  recap: 1
  preview: 1
