ViuTV:
  name:
    - ViuTV
  scraper:
    xmltv: 410274@http://epg.pw/xmltv/epg_HK.xml 
  refresh: today
  recap: 1
  preview: 1
Now新聞台:
  name:
    - Now新聞台
  scraper:
    xmltv: 410344@http://epg.pw/xmltv/epg_HK.xml 
  refresh: today
  recap: 1
  preview: 1
CWIN:
  name:
    - SUPER FREE
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SVAR:
  name:
    - SUPER獎門人
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SEYT:
  name:
    - SUPER EYT
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SFOO:
  name:
    - SUPER識食
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
STRA:
  name:
    - SUPER識嘆
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SMUS:
  name:
    - SUPER Music
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SGOL:
  name:
    - SUPER金曲
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SSIT:
  name:
    - SUPER煲劇
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
STVM:
  name:
    - SUPER劇場
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SDOC:
  name:
    - SUPER話當年
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SSPT:
  name:
    - SUPER Sports
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
C18:
  name:
    - myTV SUPER 18台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
C28:
  name:
    - 28AI智慧賽馬
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
TVG:
  name:
    - 黃金翡翠台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
J:
  name:
    - 翡翠台
    - 翡翠台(超高清)
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
B:
  name:
    - TVB Plus
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
C:
  name:
    - 無綫新聞台
    - 互動窗 1
    - 互動窗 2
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
P:
  name:
    - 明珠台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTVC:
  name:
    - 千禧經典台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTVS:
  name:
    - 亞洲劇台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CDR3:
  name:
    - 華語劇台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
TVO:
  name:
    - 黃金華劇台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTVE:
  name:
    - 娛樂新聞台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCOC:
  name:
    - 戲曲台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
KID:
  name:
    - SUPER Kids Channel
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
ZOO:
  name:
    - ZooMoo
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CNIKO:
  name:
    - Nickelodeon
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CNIJR:
  name:
    - Nick Jr
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCLM:
  name:
    - 粵語片台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CMAM:
  name:
    - 美亞電影台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTHR:
  name:
    - Thrill
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCCM:
  name:
    - 天映經典頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CMC:
  name:
    - 中國電影頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CRTX:
  name:
    - ROCK Action
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
POPC:
  name:
    - PopC
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
ACTM:
  name:
    - Action Hollywood Movies
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
RCM:
  name:
    - Rialto Classic Movies (RCM)
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CKIX:
  name:
    - KIX
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
TRSP:
  name:
    - TRACE Sport Stars
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
LNH:
  name:
    - Love Nature HD
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
LN4:
  name:
    - Love Nature 4K
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SMS:
  name:
    - Global Trekker
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
PETC:
  name:
    - Pet Club TV
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
GLBT:
  name:
    - Globetrotter
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
DOCV:
  name:
    - Docsville
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
PULS:
  name:
    - Pulse Documentaries
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CRTE:
  name:
    - ROCK綜藝娛樂
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CAXN:
  name:
    - AXN
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CANI:
  name:
    - Animax
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CJTV:
  name:
    - tvN
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTS1:
  name:
    - 無線衛星亞洲台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CRE:
  name:
    - 創世電視
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
FBX:
  name:
    - FashionBox
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CMEZ:
  name:
    - Mezzo Live HD
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CC1:
  name:
    - 中央電視台綜合頻道 (港澳版)
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CGD:
  name:
    - CGTN (中國環球電視網)記錄頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CGE:
  name:
    - CGTN (中國環球電視網)英語頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
DTV:
  name:
    - 東方衛視國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
PCC:
  name:
    - 鳳凰衛視中文台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
PIN:
  name:
    - 鳳凰衛視資訊台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
PHK:
  name:
    - 鳳凰衛視香港台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CC4:
  name:
    - 中國中央電視台中文國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCE:
  name:
    - 中國中央電視台娛樂頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCO:
  name:
    - 中國中央電視台戲曲頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
YNTV:
  name:
    - 雲南瀾湄國際衛視
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
AHTV:
  name:
    - 安徽廣播電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
BJTV:
  name:
    - 北京電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
GXTV:
  name:
    - 廣西電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
FJTV:
  name:
    - 福建海峽衛視國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
HNTV:
  name:
    - 湖南電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
JSTV:
  name:
    - 江蘇電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
GBTV:
  name:
    - 廣東廣播電視台大灣區衛視頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
ZJTV:
  name:
    - 浙江電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SZTV:
  name:
    - 深圳衛視國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
NOW7:
  name:
    - NOW 70s
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
NOW8:
  name:
    - NOW 80s
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
NOWR:
  name:
    - NOW ROCK
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
NOW9:
  name:
    - NOW 90s00s
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CONC:
  name:
    - Concerto
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
TRUR:
  name:
    - TRACE Urban
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTSN:
  name:
    - 無線衛星新聞台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCNA:
  name:
    - 亞洲新聞台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CJAZ:
  name:
    - 半島電視台英語頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CF24:
  name:
    - France 24
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CDW1:
  name:
    - DW
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CNHK:
  name:
    - NHK World-Japan
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CARI:
  name:
    - Arirang TV
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
NSWD:
  name:
    - NewsWorld
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT2:
  name:
    - myTV SUPER直播足球2台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT3:
  name:
    - myTV SUPER直播足球3台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT4:
  name:
    - myTV SUPER直播足球4台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT5:
  name:
    - myTV SUPER直播足球5台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT6:
  name:
    - myTV SUPER直播足球6台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT7:
  name:
    - myTV SUPER直播足球7台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
TEST:
  name:
    - 測試頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1


