东南卫视:
  name:
    - 东南卫视
  scraper:
    tvmao: FJTV2
  refresh: today
  recap: 1
  preview: 2
广西卫视:
  name:
    - 广西卫视
  scraper:
    tvmao: GUANXI1
  refresh: today
  recap: 1
  preview: 2
吉林卫视:
  name:
    - 吉林卫视
  scraper:
    tvmao: JILIN1
  refresh: today
  recap: 1
  preview: 2
青海卫视:
  name:
    - 青海卫视
  scraper:
    tvmao: QHTV1
  refresh: today
  recap: 1
  preview: 2
海南卫视:
  name:
    - 海南卫视
  scraper:
    tvmao: TCTC1
  refresh: today
  recap: 1
  preview: 2
甘肃卫视:
  name:
    - 甘肃卫视
  scraper:
    tvmao: GSTV1
  refresh: today
  recap: 1
  preview: 2
三沙卫视:
  name:
    - 三沙卫视
  scraper:
    tvmao: SANSHATV
  refresh: today
  recap: 1
  preview: 2
云南卫视:
  name:
    - 云南卫视
  scraper:
    tvmao: YNTV1
  refresh: today
  recap: 1
  preview: 2
重庆卫视:
  name:
    - 重庆卫视
  scraper:
    tvmao: CCQTV1
  refresh: today
  recap: 1
  preview: 2

  