# http://epg.pw/xmltv/epg_HK.xml
ViuTV:
  name:
    - ViuTV
  scraper:
    xmltv: 410274@http://epg.pw/xmltv/epg_HK.xml 
  refresh: today
  recap: 1
  preview: 1
Now新闻台:
  name:
    - Now新聞台
  scraper:
    xmltv: 410344@http://epg.pw/xmltv/epg_HK.xml 
  refresh: today
  recap: 1
  preview: 1

HOY76:
  name:
    - HOY76
  scraper:
    xmltv: HOY76@http://epg.112114.xyz/pp.xml 
  refresh: today
  recap: 1
  preview: 1
HOY77:
  name:
    - HOY77
  scraper:
    xmltv: HOY77@http://epg.112114.xyz/pp.xml 
  refresh: today
  recap: 1
  preview: 1
HOY78:
  name:
    - HOY78
  scraper:
    xmltv: HOY78@http://epg.112114.xyz/pp.xml 
  refresh: today
  recap: 1
  preview: 1

# mytvsuper
CWIN:
  name:
    - SUPER FREE
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SVAR:
  name:
    - SUPER獎門人
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SEYT:
  name:
    - SUPER EYT
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SFOO:
  name:
    - SUPER識食
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
STRA:
  name:
    - SUPER識嘆
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SMUS:
  name:
    - SUPER Music
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SGOL:
  name:
    - SUPER金曲
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SSIT:
  name:
    - SUPER煲劇
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
STVM:
  name:
    - SUPER劇場
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SDOC:
  name:
    - SUPER話當年
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SSPT:
  name:
    - SUPER Sports
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
C18:
  name:
    - myTV SUPER 18台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
C28:
  name:
    - 28AI智慧賽馬
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
TVG:
  name:
    - 黃金翡翠台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
J:
  name:
    - 翡翠台
    - 翡翠台(超高清)
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
B:
  name:
    - TVB Plus
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
C:
  name:
    - 無綫新聞台
    - 互動窗 1
    - 互動窗 2
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
P:
  name:
    - 明珠台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTVC:
  name:
    - 千禧經典台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTVS:
  name:
    - 亞洲劇台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CDR3:
  name:
    - 華語劇台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
TVO:
  name:
    - 黃金華劇台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTVE:
  name:
    - 娛樂新聞台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCOC:
  name:
    - 戲曲台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
KID:
  name:
    - SUPER Kids Channel
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
ZOO:
  name:
    - ZooMoo
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CNIKO:
  name:
    - Nickelodeon
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CNIJR:
  name:
    - Nick Jr
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCLM:
  name:
    - 粵語片台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CMAM:
  name:
    - 美亞電影台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTHR:
  name:
    - Thrill
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCCM:
  name:
    - 天映經典頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CMC:
  name:
    - 中國電影頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CRTX:
  name:
    - ROCK Action
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
POPC:
  name:
    - PopC
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
ACTM:
  name:
    - Action Hollywood Movies
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
RCM:
  name:
    - Rialto Classic Movies (RCM)
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CKIX:
  name:
    - KIX
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
TRSP:
  name:
    - TRACE Sport Stars
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
LNH:
  name:
    - Love Nature HD
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
LN4:
  name:
    - Love Nature 4K
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SMS:
  name:
    - Global Trekker
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
PETC:
  name:
    - Pet Club TV
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
GLBT:
  name:
    - Globetrotter
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
DOCV:
  name:
    - Docsville
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
PULS:
  name:
    - Pulse Documentaries
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CRTE:
  name:
    - ROCK綜藝娛樂
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CAXN:
  name:
    - AXN
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CANI:
  name:
    - Animax
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CJTV:
  name:
    - tvN
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTS1:
  name:
    - 無線衛星亞洲台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CRE:
  name:
    - 創世電視
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
FBX:
  name:
    - FashionBox
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CMEZ:
  name:
    - Mezzo Live HD
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CC1:
  name:
    - 中央電視台綜合頻道 (港澳版)
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CGD:
  name:
    - CGTN (中國環球電視網)記錄頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CGE:
  name:
    - CGTN (中國環球電視網)英語頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
DTV:
  name:
    - 東方衛視國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
PCC:
  name:
    - 鳳凰衛視中文台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
PIN:
  name:
    - 鳳凰衛視資訊台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
PHK:
  name:
    - 鳳凰衛視香港台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CC4:
  name:
    - 中國中央電視台中文國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCE:
  name:
    - 中國中央電視台娛樂頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCO:
  name:
    - 中國中央電視台戲曲頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
YNTV:
  name:
    - 雲南瀾湄國際衛視
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
AHTV:
  name:
    - 安徽廣播電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
BJTV:
  name:
    - 北京電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
GXTV:
  name:
    - 廣西電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
FJTV:
  name:
    - 福建海峽衛視國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
HNTV:
  name:
    - 湖南電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
JSTV:
  name:
    - 江蘇電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
GBTV:
  name:
    - 廣東廣播電視台大灣區衛視頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
ZJTV:
  name:
    - 浙江電視台國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
SZTV:
  name:
    - 深圳衛視國際頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
NOW7:
  name:
    - NOW 70s
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
NOW8:
  name:
    - NOW 80s
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
NOWR:
  name:
    - NOW ROCK
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
NOW9:
  name:
    - NOW 90s00s
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CONC:
  name:
    - Concerto
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
TRUR:
  name:
    - TRACE Urban
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CTSN:
  name:
    - 無線衛星新聞台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CCNA:
  name:
    - 亞洲新聞台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CJAZ:
  name:
    - 半島電視台英語頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CF24:
  name:
    - France 24
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CDW1:
  name:
    - DW
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CNHK:
  name:
    - NHK World-Japan
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
CARI:
  name:
    - Arirang TV
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
NSWD:
  name:
    - NewsWorld
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT2:
  name:
    - myTV SUPER直播足球2台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT3:
  name:
    - myTV SUPER直播足球3台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT4:
  name:
    - myTV SUPER直播足球4台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT5:
  name:
    - myTV SUPER直播足球5台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT6:
  name:
    - myTV SUPER直播足球6台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
EVT7:
  name:
    - myTV SUPER直播足球7台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1
TEST:
  name:
    - 測試頻道
  scraper:
    mytvsuper: 
  refresh: today
  recap: 1
  preview: 1

# cctv
CCTV1:
  name:
    - CCTV1
  scraper:
    tvmao: CCTV1
  refresh: today
  recap: 1
  preview: 1
CCTV2:
  name:
    - CCTV2
  scraper:
    tvmao: CCTV2
  refresh: today
  recap: 1
  preview: 1
CCTV3:
  name:
    - CCTV3
  scraper:
    tvmao: CCTV3
  refresh: today
  recap: 1
  preview: 1
CCTV4:
  name:
    - CCTV4
  scraper:
    tvmao: CCTV4
  refresh: today
  recap: 1
  preview: 1
CCTV5:
  name:
    - CCTV5
  scraper:
    tvmao: CCTV5
  refresh: today
  recap: 1
  preview: 1
CCTV5+:
  name:
    - CCTV5+
  scraper:
    tvmao: CCTV5+
  refresh: today
  recap: 1
  preview: 1
CCTV6:
  name:
    - CCTV6
  scraper:
    tvmao: CCTV6
  refresh: today
  recap: 1
  preview: 1
CCTV7:
  name:
    - CCTV7
  scraper:
    tvmao: CCTV7
  refresh: today
  recap: 1
  preview: 1
CCTV8:
  name:
    - CCTV8
  scraper:
    tvmao: CCTV8
  refresh: today
  recap: 1
  preview: 1
CCTV9:
  name:
    - CCTV9
  scraper:
    tvmao: CCTV9
  refresh: today
  recap: 1
  preview: 1
CCTV10:
  name:
    - CCTV10
  scraper:
    tvmao: CCTV10
  refresh: today
  recap: 1
  preview: 1
CCTV11:
  name:
    - CCTV11
  scraper:
    tvmao: CCTV11
  refresh: today
  recap: 1
  preview: 1
CCTV12:
  name:
    - CCTV12
  scraper:
    tvmao: CCTV12
  refresh: today
  recap: 1
  preview: 1
CCTV13:
  name:
    - CCTV13
  scraper:
    tvmao: CCTV13
  refresh: today
  recap: 1
  preview: 1
CCTV14:
  name:
    - CCTV14
  scraper:
    tvmao: CCTV14
  refresh: today
  recap: 1
  preview: 1
CCTV15:
  name:
    - CCTV-15
  scraper:
    tvmao: CCTV15
  refresh: today
  recap: 1
  preview: 1
CCTV16:
  name:
    - CCTV16
  scraper:
    tvmao: CCTV16
  refresh: today
  recap: 1
  preview: 1
CCTV17:
  name:
    - CCTV17
  scraper:
    tvmao: CCTV17
  refresh: today
  recap: 1
  preview: 1

风云足球:
  name:
    - 风云足球
  scraper:
    tvmao: CCTVPAYFEE1
  refresh: today
  recap: 1
  preview: 1
风云音乐:
  name:
    - 风云音乐
  scraper:
    tvmao: CCTVPAYFEE2
  refresh: today
  recap: 1
  preview: 1
第一剧场:
  name:
    - 第一剧场
  scraper:
    tvmao: CCTVPAYFEE3
  refresh: today
  recap: 1
  preview: 1
风云剧场:
  name:
    - 风云剧场
  scraper:
    tvmao: CCTVPAYFEE4
  refresh: today
  recap: 1
  preview: 1
世界地理:
  name:
    - 世界地理
  scraper:
    tvmao: CCTVPAYFEE5
  refresh: today
  recap: 1
  preview: 1
电视指南:
  name:
    - 电视指南
  scraper:
    tvmao: CCTVPAYFEE6
  refresh: today
  recap: 1
  preview: 1
怀旧剧场:
  name:
    - 怀旧剧场
  scraper:
    tvmao: CCTVPAYFEE7
  refresh: today
  recap: 1
  preview: 1
兵器科技:
  name:
    - 兵器科技
  scraper:
    tvmao: CCTVPAYFEE8
  refresh: today
  recap: 1
  preview: 1
女性时尚:
  name:
    - 女性时尚
  scraper:
    tvmao: CCTVPAYFEE9
  refresh: today
  recap: 1
  preview: 1
高尔夫网球:
  name:
    - 高尔夫网球
  scraper:
    tvmao: CCTVPAYFEE13
  refresh: today
  recap: 1
  preview: 1
央视文化精品:
  name:
    - 央视文化精品
  scraper:
    tvmao: CCTVPAYFEE14
  refresh: today
  recap: 1
  preview: 1
央视台球:
  name:
    - 央视台球
  scraper:
    tvmao: CCTVPAYFEE36
  refresh: today
  recap: 1
  preview: 1

# 卫视
广东卫视:
  name:
    - 广东卫视
  scraper:
    tvmao: GDTV1
  refresh: today
  recap: 1
  preview: 1
大湾区卫视:
  name:
    - 大湾区卫视
  scraper:
    tvmao: NANFANG6
  refresh: today
  recap: 1
  preview: 1
深圳卫视:
  name:
    - 深圳卫视
  scraper:
    tvmao: SZTV1
  refresh: today
  recap: 1
  preview: 1
湖南卫视:
  name:
    - 湖南卫视
  scraper:
    tvmao: HUNANTV1
  refresh: today
  recap: 1
  preview: 1
浙江卫视:
  name:
    - 浙江卫视
  scraper:
    tvmao: ZJTV1
  refresh: today
  recap: 1
  preview: 1
江苏卫视:
  name:
    - 江苏卫视
  scraper:
    tvmao: JSTV1
  refresh: today
  recap: 1
  preview: 1
东方卫视:
  name:
    - 东方卫视
  scraper:
    tvmao: DONGFANG1
  refresh: today
  recap: 1
  preview: 1
安徽卫视:
  name:
    - 安徽卫视
  scraper:
    tvmao: AHTV1
  refresh: today
  recap: 1
  preview: 1
北京卫视:
  name:
    - 北京卫视
  scraper:
    tvmao: BTV1
  refresh: today
  recap: 1
  preview: 1
天津卫视:
  name:
    - 天津卫视
  scraper:
    tvmao: TJTV1
  refresh: today
  recap: 1
  preview: 1
山东卫视:
  name:
    - 山东卫视
  scraper:
    tvmao: SDTV1
  refresh: today
  recap: 1
  preview: 1
江西卫视:
  name:
    - 江西卫视
  scraper:
    tvmao: JXTV1
  refresh: today
  recap: 1
  preview: 1
湖北卫视:
  name:
    - 湖北卫视
  scraper:
    tvmao: HUBEI1
  refresh: today
  recap: 1
  preview: 1
辽宁卫视:
  name:
    - 辽宁卫视
  scraper:
    tvmao: LNTV1
  refresh: today
  recap: 1
  preview: 1
黑龙江卫视:
  name:
    - 黑龙江卫视
  scraper:
    tvmao: HLJTV1
  refresh: today
  recap: 1
  preview: 1
贵州卫视:
  name:
    - 贵州卫视
  scraper:
    tvmao: GUIZOUTV1
  refresh: today
  recap: 1
  preview: 1
四川卫视:
  name:
    - 四川卫视
  scraper:
    tvmao: SCTV1
  refresh: today
  recap: 1
  preview: 1
河南卫视:
  name:
    - 河南卫视
  scraper:
    tvmao: HNTV1
  refresh: today
  recap: 1
  preview: 1
云南卫视:
  name:
    - 云南卫视
  scraper:
    tvmao: YNTV1
  refresh: today
  recap: 1
  preview: 1
重庆卫视:
  name:
    - 重庆卫视
  scraper:
    tvmao: CCQTV1
  refresh: today
  recap: 1
  preview: 1
河北卫视:
  name:
    - 河北卫视
  scraper:
    tvmao: HEBEI1
  refresh: today
  recap: 1
  preview: 1
东南卫视:
  name:
    - 东南卫视
  scraper:
    tvmao: FJTV2
  refresh: today
  recap: 1
  preview: 1
广西卫视:
  name:
    - 广西卫视
  scraper:
    tvmao: GUANXI1
  refresh: today
  recap: 1
  preview: 1
吉林卫视:
  name:
    - 吉林卫视
  scraper:
    tvmao: JILIN1
  refresh: today
  recap: 1
  preview: 1
青海卫视:
  name:
    - 青海卫视
  scraper:
    tvmao: QHTV1
  refresh: today
  recap: 1
  preview: 1
海南卫视:
  name:
    - 海南卫视
  scraper:
    tvmao: TCTC1
  refresh: today
  recap: 1
  preview: 1
甘肃卫视:
  name:
    - 甘肃卫视
  scraper:
    tvmao: GSTV1
  refresh: today
  recap: 1
  preview: 1
三沙卫视:
  name:
    - 三沙卫视
  scraper:
    tvmao: SANSHATV
  refresh: today
  recap: 1
  preview: 1
  